apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-registry
  labels:
    app: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}