name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      DOCKER_DRIVER: overlay2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show Docker info
        run: docker info

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get build name
        id: get_build_name
        run: |
          BUILD_NAME=$(git describe --tags || echo ${{ github.run_number }})
          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
          echo "Build name: $BUILD_NAME"

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.BUILD_NAME }} \
                        -t ghcr.io/${{ github.repository }}:latest \
                        --build-arg BUILDKIT_INLINE_CACHE=1 \
                        --cache-from ghcr.io/${{ github.repository }} .
          docker push ghcr.io/${{ github.repository }} --all-tags

  build_helm_chart:
    name: Build Helm Chart
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Helm version
        run: helm version

      - name: Get build name
        run: |
          BUILD_NAME=$(git describe --tags || echo ${{ github.run_number }})
          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
          echo "Build name: $BUILD_NAME"

      - name: Package Helm chart
        run: |
          helm package charts/${{ github.event.repository.name }} --version ${{ env.BUILD_NAME }} -d .

      - name: Create GitHub Release and upload Helm chart
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.event.repository.name }}-${{ env.BUILD_NAME }}.tgz
          tag: ${{ env.BUILD_NAME }}
          name: Release ${{ env.BUILD_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true